sudo: false

language: node_js
node_js:
- '8'
- '10'
- '12'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g yarn

install:
  - yarn

script:
  - pwd
  - yarn tsc:test

after_script:
  - node ./bin/parking_lot input.txt output.txt
  - cat output.txt
